---
title: Remove 'Extract' from Context Menu
description: Removes 'Extract' from Context Menu
actions:
  - !cmd:
    command: '"CutorDesktop\4. Interface Tweaks\Context Menus\Extract\Remove Extract (default).cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated