---
title: Add Theme
description: Adds and sets the Cutor themes by default
actions:
    #Apply theme file and set recent themes
  - !powerShell:
    command: |
      .\CutorModules\initPowerShell.ps1
      Set-ThemeMRU
    wait: true
    onUpgrade: true
    oobe: true
    exeDir: true
    runas: currentUserElevated
    
  - !powerShell:
    command: |
      .\CutorModules\initPowerShell.ps1
      Set-Theme -Path """$([Environment]::GetFolderPath('Windows'))\Resources\Themes\cutor-dark.theme"""
      Set-ThemeMRU
    wait: true
    onUpgrade: false
    exeDir: true
    runas: currentUserElevated

    # Applies Cutor lockscreen background & wallpaper 
    # Also disables fun facts, tips, tricks, and more on lockscreen - only on Enterprise/Education
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization'
    value: 'LockScreenOverlaysDisabled'
    data: '1'
    type: REG_DWORD
    onUpgrade: false
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'RotatingLockScreenEnabled'
    data: '0'
    type: REG_DWORD
    onUpgrade: false
  - !powerShell:
    command: |
      foreach ($userKey in (Get-ChildItem "HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\Creative").PsPath) {
          Set-ItemProperty -Path $userKey -Name 'RotatingLockScreenEnabled' -Type DWORD -Value 0 -Force
      }
    exeDir: true
    wait: true
    onUpgrade: false
  - !powerShell:
    command: |
      .\CutorModules\initPowerShell.ps1
      Set-LockscreenImage
    exeDir: true
    wait: true
    runas: currentUserElevated
    onUpgrade: false

    # Set Cutor theme as default for new users
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Software\Policies\Microsoft\Windows\Personalization'
    value: 'ThemeFile'
    data: '%windir%\Resources\Themes\cutor-dark.theme'
    type: REG_SZ
    onUpgrade: true
    
    
