---
title: Configure OEM Information
description: Configures OEM information to contain the Cutor version and the Cutor Discord server
actions:
  - !powerShell:
    command: |
      $version = ''

      Write-Output 'Setting boot entry name...'
      bcdedit /set description """Windows $(('10', '11')[[int]([System.Environment]::OSVersion.Version.Build -ge 22000)]) $version"""

      Write-Output 'Setting other versioned OEM information...'
      $reportedVer = """Windows 11 $version"""
      # Shows in Settings
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation' -Name 'Model' -Value $reportedVer -Force
      # Shows in winver
      Set-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name 'RegisteredOrganization' -Value '' -Force
    wait: true
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Manufacturer'
    data: 'Cutorline14'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportURL'
    data: 'https://cutorline14.github.io/'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportPhone'
    data: 'https://cutorline14.github.io/'
    type: REG_SZ

