---
title: Enable Windows Recovery Environment
description: After installing Cutor, some users have reported WinRE to be disabled. This re-enables it
actions:
  - !cmd:
    command: 'reagentc /enable'
    exeDir: true
    wait: true
    runas: currentUserElevated
